#!/bin/sh
#
# @name optimAero Octarotor
# @type Octarotor x
# @class Custom
# @autostart 10024
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 2
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 8

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108

param set-default MPC_THR_HOVER 0.32
