#!/bin/sh
#
# @name optimAero USV Surface
# @type Boat
# @class Rover
# @autostart 10029
#

. ${R}etc/init.d/rc.rover_defaults

param set-default MAV_TYPE 11
param set-default CA_AIRFRAME 5
param set-default GND_SPEED_TRIM 2
param set-default GND_THR_CRUISE 0.3
param set-default NAV_ACC_RAD 1
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
