#!/bin/sh
#
# @name F16
#
# @type Fixed wing
#

. ${R}etc/init.d/rc.fw_defaults

#FW
param set-default MAV_TYPE 1
param set-default CA_AIRFRAME	1

param set-default EKF2_FUSE_BETA 1

param set-default VT_B_TRANS_DUR 5
param set-default VT_ELEV_MC_LOCK 0
param set-default VT_TYPE 0
param set-default VT_FW_DIFTHR_EN 1
param set-default VT_FW_DIFTHR_S_Y 0.3
param set-default MPC_MAN_Y_MAX 60
param set-default MC_PITCH_P 5

param set-default CBRK_AIRSPD_CHK	0
param set-default CBRK_BUZZER	0
param set-default CBRK_FLIGHTTERM 121212
param set-default CBRK_IO_SAFETY 22027
param set-default CBRK_SUPPLY_CHK 894281
param set-default CBRK_USB_CHK 197848
param set-default CBRK_VTOLARMING 159753

param set-default CA_FAILURE_MODE 0

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1 	# Is this right now that the F16 is CTOL not VTOL?
param set-default CA_ROTOR0_CT 6.5 	# Thrust coefficient (Is this needed since we're modeling the plant?)
param set-default CA_ROTOR0_KM 0 	# Rotor moment coefficient

param set-default CA_SV0_SLEW	0.0
param set-default CA_SV1_SLEW	0.0
param set-default CA_SV2_SLEW	0.0
param set-default CA_SV_CS0_FLAP	0.0
param set-default CA_SV_CS0_SPOIL	0.0
param set-default CA_SV_CS0_TRIM	0.0
param set-default CA_SV_CS0_TRQ_P	0
param set-default CA_SV_CS0_TRQ_R	-0.5
param set-default CA_SV_CS0_TRQ_Y	0.0
param set-default CA_SV_CS0_TYPE	1
param set-default CA_SV_CS1_FLAP	0.0
param set-default CA_SV_CS1_SPOIL	0.0
param set-default CA_SV_CS1_TRIM	0.0
param set-default CA_SV_CS1_TRQ_P	-1
param set-default CA_SV_CS1_TRQ_R	0
param set-default CA_SV_CS1_TRQ_Y	0.0
param set-default CA_SV_CS1_TYPE	12 	#Elevator
param set-default CA_SV_CS2_FLAP	0.0
param set-default CA_SV_CS2_SPOIL	0.0
param set-default CA_SV_CS2_TRIM	0.0
param set-default CA_SV_CS2_TRQ_P	0.0
param set-default CA_SV_CS2_TRQ_R	0.0
param set-default CA_SV_CS2_TRQ_Y	-1
param set-default CA_SV_CS2_TYPE	4 #Rudder
param set-default CA_SV_CS_COUNT	3

param set-default COM_DISARM_PRFLT 0

param set-default PWM_MAIN_FUNC1 101  #ENGINE
param set-default PWM_MAIN_FUNC2 201  #AILERONS
param set-default PWM_MAIN_FUNC3 202  #ELEVATOR
param set-default PWM_MAIN_FUNC4 203  #RUDDER

# STABILIZE MODE PARAMS
param set-default FW_AIRSPD_MAX  900 # mps
param set-default FW_AIRSPD_MIN  100 # mps
param set-default FW_AIRSPD_TRIM 275 # mps
param set-default FW_PSP_OFF 	 0   # set to the pitch angle required to masintain level flight in stabilize (deg)
param set-default FW_THR_TRIM 	 0.75
param set-default FW_THR_ASPD_MAX 1  # nd
param set-default FW_THR_ASPD_MIN 0.4 #nd Throttle at min airspeed.
param set-default FW_MAN_P_MAX 20 #Max pitch setpoint in attitude stabilized mode. Default: 45 degrees.
param set-default FW_T_SINK_R_SP 1 # Max sink rate setpoint
param set-default FW_T_CLMB_R_SP 1 # Max clib rate setpoint

# Roll Gains
param set-default FW_R_TC 0.2 # Roll time constant (s)
param set-default FW_RR_P 0.0001 # Roll rate proportional gain rad/s
param set-default FW_RR_I  0
param set-default FW_RR_FF 0.05
param set-default FW_R_RMAX 90 #Maximum roll rate setpointdeg/s
param set-default FW_R_LIM 65 # Maximum roll angle

# Pitch Gains
param set-default FW_P_RMAX_POS 90 #Maximum pitch rate setpointdeg/s
param set-default FW_P_LIM_MAX 60 # Maximum pitch angle
param set-default FW_P_LIM_MIN -60 # Maximum pitch angle

# Yaw gains
param set-default FW_YR_P 0.010 # rad/s

# Airspeed params
param set-default ASPD_FS_T_STOP 10 #s
param set-default ASPD_FALLBACK_GW  1
param set-default ASPD_FS_INNOV  9.98	#19.4 kn

# GYRO STUFF
param set-default EKF2_GYR_B_NOISE 0.001 #rad/s^2

# EKF
param set-default EKF2_GPS_CHECK 21
param set-default EKF2_GPS_CTRL 3
param set-default EKF2_MAG_ACCLIM 0.00
param set-default EKF2_MAG_E_NOISE 0.00
param set-default EKF2_MAG_NOISE 0.001 #gauss
param set-default EKF2_MAG_CHECK 0
param set-default EKF2_IMU_CTRL 1



