#!/bin/sh
#
# @name optimAero eVTOL
# @type VTOL Tiltrotor
# @class VTOL
# @autostart 10025
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default MAV_TYPE 22
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

param set-default MPC_THR_HOVER 0.32
