#!/bin/sh
#
# @name optimAero NPS AUV
# @type Submarine
# @class Rover
# @autostart 10039
#

. ${R}etc/init.d/rc.rover_defaults

# Cruise-mission AUV (Naval Postgraduate School design, real L=5.3 m / mass=5443 kg from
# MSS/CRAFT/AUV/models/npsauv.m) -- twin-thruster differential mixer, same class as
# 10033_optimAeroUUV (uuv_subsea/remus100). Distinct mission profile (cruise/inspection vs.
# uuv_subsea's general-purpose torpedo shape) -- see
# vehicle/common/setUpVehicle.m's "uuv_npsauv" case and PLAN_VEHICULOS_AEREOS_Y_MARINOS_SITL.md.
param set-default MAV_TYPE 12
param set-default CA_AIRFRAME 5
param set-default GND_SPEED_TRIM 1.5
param set-default GND_THR_CRUISE 0.25
param set-default NAV_ACC_RAD 1
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
