#!/bin/sh
#
# @name optimAero Bicycle Rover
# @type Rover
# @class Rover
# @autostart 10034
#

. ${R}etc/init.d/rc.rover_defaults

param set-default MAV_TYPE 10
param set-default CA_AIRFRAME 5
param set-default GND_WHEEL_BASE 1.2
param set-default GND_MAX_ANG 0.6
param set-default GND_SPEED_TRIM 3
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 101
